migrate:
  file:
    # 在迁移文件的时候，对以存在的文件进行的操作（replace替换，keep保留, query询问）
    copy-option: keep
  excludes:
  - assets
  - data
  - debug
  - libraries
  - logs
  - PCL
  filter_rule: excludes
  screenshots: true
